[build-system]
requires = ["poetry-core>=1.6.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "3.11.3"
customtkinter = "5.1.3"
pygame = "2.3.0"
pgu = "0.21"
